create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.products (
  id text primary key,
  name text not null,
  description text not null default '',
  category text not null,
  unit text not null,
  price_cup integer not null check (price_cup >= 0),
  stock numeric(12, 3) not null default 0 check (stock >= 0),
  minimum_step numeric(12, 3) not null default 1 check (minimum_step > 0),
  emoji text not null default '🥩',
  accent text not null default '#d92525',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index products_active_category_idx
  on public.products (active, category, name);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  display_id text not null unique,
  customer_name text not null,
  phone text not null,
  delivery_method text not null check (delivery_method in ('recoger', 'domicilio')),
  address text not null default '',
  payment_method text not null check (payment_method in ('Transfermóvil', 'Efectivo')),
  notes text not null default '',
  total_cup integer not null check (total_cup >= 0),
  status text not null default 'pendiente'
    check (status in ('pendiente', 'confirmado', 'pagado', 'listo', 'completado', 'cancelado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index orders_status_created_idx
  on public.orders (status, created_at desc);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null references public.products(id),
  product_name text not null,
  quantity numeric(12, 3) not null check (quantity > 0),
  unit text not null,
  price_each_cup integer not null check (price_each_cup >= 0),
  subtotal_cup integer not null check (subtotal_cup >= 0)
);

create index order_items_order_id_idx on public.order_items (order_id);

create table public.settings (
  id text primary key,
  business_name text not null,
  whatsapp_phone text not null default '',
  pickup_address text not null default '',
  payment_copy text not null default '',
  updated_at timestamptz not null default now()
);

create table private.admin_credentials (
  id text primary key,
  password_hash text not null,
  session_hours integer not null default 168 check (session_hours between 1 and 720),
  updated_at timestamptz not null default now()
);

create table private.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index admin_sessions_expires_at_idx on private.admin_sessions (expires_at);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.settings enable row level security;

revoke all on table public.products, public.orders, public.order_items, public.settings
  from public, anon, authenticated;
revoke all on all tables in schema private from public, anon, authenticated;
revoke all on all sequences in schema public from public, anon, authenticated;

insert into public.products
  (id, name, description, category, unit, price_cup, stock, minimum_step, emoji, accent, active)
values
  ('chorizo-criollo', 'Chorizo criollo', 'Sazonado en casa, jugoso y listo para la sartén.', 'Embutidos', 'paquete de 500 g', 680, 16, 1, '🌭', '#ef3d30', true),
  ('hamburguesas-caseras', 'Hamburguesas caseras', 'Cuatro unidades de cerdo condimentadas y listas para cocinar.', 'Listos para cocinar', 'paquete de 4', 850, 12, 1, '🍔', '#f08a24', true),
  ('picadillo-condimentado', 'Picadillo condimentado', 'Mezcla fresca con el punto justo de especias.', 'Preparados', 'paquete de 1 kg', 1150, 9, 1, '🥩', '#bb2030', true),
  ('jamon-prensado', 'Jamón prensado', 'Suave, rendidor y perfecto para panes y meriendas.', 'Embutidos', 'paquete de 500 g', 720, 6, 1, '🍖', '#d95e38', true),
  ('croquetas-jamon', 'Croquetas de jamón', 'Crujientes por fuera, cremosas por dentro.', 'Listos para cocinar', 'paquete de 10', 550, 20, 1, '🟠', '#e0a124', true),
  ('albondigas-criollas', 'Albóndigas criollas', 'Preparadas a mano para resolver una comida completa.', 'Preparados', 'paquete de 12', 780, 0, 1, '🍲', '#8f2834', true);

insert into public.settings
  (id, business_name, whatsapp_phone, pickup_address, payment_copy)
values
  ('main', 'Don Padrón', '', 'Punto de elaboración Don Padrón',
   'Paga por Transfermóvil o en efectivo. Los datos exactos se confirman por WhatsApp.');

create or replace function private.has_admin_session(p_token text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    p_token is not null
    and length(p_token) = 64
    and exists (
      select 1
      from private.admin_sessions s
      where s.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
        and s.expires_at > now()
    );
$$;

revoke all on function private.has_admin_session(text) from public, anon, authenticated;

create or replace function public.get_catalog()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'products', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', p.id,
          'name', p.name,
          'description', p.description,
          'category', p.category,
          'unit', p.unit,
          'priceCup', p.price_cup,
          'stock', p.stock,
          'minimumStep', p.minimum_step,
          'emoji', p.emoji,
          'accent', p.accent
        ) order by p.category, p.name
      )
      from public.products p
      where p.active
    ), '[]'::jsonb),
    'settings', coalesce((
      select jsonb_build_object(
        'businessName', s.business_name,
        'whatsappPhone', s.whatsapp_phone,
        'pickupAddress', s.pickup_address,
        'paymentCopy', s.payment_copy
      )
      from public.settings s
      where s.id = 'main'
    ), '{}'::jsonb)
  );
$$;

create or replace function public.place_order(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_customer_name text := btrim(coalesce(p_payload ->> 'customerName', ''));
  v_phone text := btrim(coalesce(p_payload ->> 'phone', ''));
  v_delivery_method text := btrim(coalesce(p_payload ->> 'deliveryMethod', 'recoger'));
  v_address text := btrim(coalesce(p_payload ->> 'address', ''));
  v_payment_method text := btrim(coalesce(p_payload ->> 'paymentMethod', 'Efectivo'));
  v_notes text := left(btrim(coalesce(p_payload ->> 'notes', '')), 300);
  v_items jsonb := p_payload -> 'items';
  v_item jsonb;
  v_product public.products%rowtype;
  v_product_id text;
  v_quantity numeric(12, 3);
  v_subtotal integer;
  v_total integer := 0;
  v_order_id uuid := gen_random_uuid();
  v_display_id text;
  v_seen text[] := array[]::text[];
  v_settings public.settings%rowtype;
begin
  if v_customer_name = '' or length(regexp_replace(v_phone, '\D', '', 'g')) < 8 then
    raise exception using errcode = '22023', message = 'Escribe tu nombre y un teléfono válido.';
  end if;

  if v_delivery_method not in ('recoger', 'domicilio') then
    raise exception using errcode = '22023', message = 'Forma de entrega inválida.';
  end if;

  if v_delivery_method = 'domicilio' and v_address = '' then
    raise exception using errcode = '22023', message = 'Escribe la dirección de entrega.';
  end if;

  if v_payment_method not in ('Transfermóvil', 'Efectivo') then
    raise exception using errcode = '22023', message = 'Forma de pago inválida.';
  end if;

  if jsonb_typeof(v_items) <> 'array'
     or jsonb_array_length(v_items) < 1
     or jsonb_array_length(v_items) > 20 then
    raise exception using errcode = '22023', message = 'Añade al menos un producto al pedido.';
  end if;

  v_display_id := 'DP-' || upper(substr(replace(v_order_id::text, '-', ''), 1, 6));

  insert into public.orders
    (id, display_id, customer_name, phone, delivery_method, address,
     payment_method, notes, total_cup)
  values
    (v_order_id, v_display_id, v_customer_name, v_phone, v_delivery_method,
     v_address, v_payment_method, v_notes, 0);

  for v_item in
    select value
    from jsonb_array_elements(v_items)
    order by value ->> 'productId'
  loop
    v_product_id := btrim(coalesce(v_item ->> 'productId', ''));

    if v_product_id = '' or jsonb_typeof(v_item -> 'quantity') <> 'number' then
      raise exception using errcode = '22023', message = 'Revisa los productos del pedido.';
    end if;

    v_quantity := (v_item ->> 'quantity')::numeric;

    if v_quantity <= 0 or v_product_id = any(v_seen) then
      raise exception using errcode = '22023', message = 'Revisa las cantidades del pedido.';
    end if;
    v_seen := array_append(v_seen, v_product_id);

    select * into v_product
    from public.products
    where id = v_product_id
    for update;

    if not found or not v_product.active then
      raise exception using errcode = 'P0001', message = 'Uno de los productos ya no está disponible.';
    end if;

    if v_quantity > v_product.stock then
      raise exception using errcode = 'P0001',
        message = format('Solo quedan %s de %s.', v_product.stock, v_product.name);
    end if;

    if abs((v_quantity / v_product.minimum_step) - round(v_quantity / v_product.minimum_step)) > 0.0001 then
      raise exception using errcode = '22023', message = format('Revisa la cantidad de %s.', v_product.name);
    end if;

    v_subtotal := round(v_product.price_cup * v_quantity)::integer;
    v_total := v_total + v_subtotal;

    insert into public.order_items
      (order_id, product_id, product_name, quantity, unit, price_each_cup, subtotal_cup)
    values
      (v_order_id, v_product.id, v_product.name, v_quantity, v_product.unit,
       v_product.price_cup, v_subtotal);

    update public.products
    set stock = stock - v_quantity, updated_at = now()
    where id = v_product.id;
  end loop;

  update public.orders
  set total_cup = v_total, updated_at = now()
  where id = v_order_id;

  select * into v_settings from public.settings where id = 'main';

  return jsonb_build_object(
    'order', jsonb_build_object(
      'id', v_order_id,
      'displayId', v_display_id,
      'totalCup', v_total
    ),
    'settings', jsonb_build_object(
      'whatsappPhone', coalesce(v_settings.whatsapp_phone, ''),
      'pickupAddress', coalesce(v_settings.pickup_address, ''),
      'paymentCopy', coalesce(v_settings.payment_copy, '')
    )
  );
end;
$$;

create or replace function public.admin_login(p_password text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_hash text;
  v_hours integer;
  v_token text;
begin
  if p_password is null or length(p_password) < 8 or length(p_password) > 256 then
    perform pg_sleep(0.35);
    return null;
  end if;

  select password_hash, session_hours into v_hash, v_hours
  from private.admin_credentials
  where id = 'main';

  if v_hash is null or extensions.crypt(p_password, v_hash) <> v_hash then
    perform pg_sleep(0.35);
    return null;
  end if;

  delete from private.admin_sessions where expires_at <= now();
  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  insert into private.admin_sessions (token_hash, expires_at)
  values (
    encode(extensions.digest(v_token, 'sha256'), 'hex'),
    now() + make_interval(hours => v_hours)
  );

  return v_token;
end;
$$;

create or replace function public.admin_logout(p_token text)
returns void
language sql
security definer
set search_path = ''
as $$
  delete from private.admin_sessions
  where token_hash = encode(extensions.digest(coalesce(p_token, ''), 'sha256'), 'hex');
$$;

create or replace function public.admin_dashboard(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.has_admin_session(p_token) then
    raise exception using errcode = '42501', message = 'La sesión administrativa venció.';
  end if;

  return jsonb_build_object(
    'products', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', p.id,
          'name', p.name,
          'category', p.category,
          'unit', p.unit,
          'priceCup', p.price_cup,
          'stock', p.stock,
          'minimumStep', p.minimum_step,
          'emoji', p.emoji,
          'active', p.active
        ) order by p.category, p.name
      )
      from public.products p
    ), '[]'::jsonb),
    'orders', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', o.id,
          'displayId', o.display_id,
          'customerName', o.customer_name,
          'phone', o.phone,
          'deliveryMethod', o.delivery_method,
          'address', o.address,
          'paymentMethod', o.payment_method,
          'notes', o.notes,
          'totalCup', o.total_cup,
          'status', o.status,
          'createdAt', o.created_at,
          'items', coalesce((
            select jsonb_agg(
              jsonb_build_object(
                'id', i.id,
                'productId', i.product_id,
                'productName', i.product_name,
                'quantity', i.quantity,
                'unit', i.unit,
                'priceEachCup', i.price_each_cup,
                'subtotalCup', i.subtotal_cup
              ) order by i.id
            )
            from public.order_items i
            where i.order_id = o.id
          ), '[]'::jsonb)
        ) order by o.created_at desc
      )
      from (
        select * from public.orders order by created_at desc limit 80
      ) o
    ), '[]'::jsonb),
    'settings', coalesce((
      select jsonb_build_object(
        'businessName', s.business_name,
        'whatsappPhone', s.whatsapp_phone,
        'pickupAddress', s.pickup_address,
        'paymentCopy', s.payment_copy
      )
      from public.settings s
      where s.id = 'main'
    ), '{}'::jsonb)
  );
end;
$$;

create or replace function public.admin_update_product(
  p_token text,
  p_product_id text,
  p_stock numeric,
  p_price_cup integer,
  p_active boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.has_admin_session(p_token) then
    raise exception using errcode = '42501', message = 'La sesión administrativa venció.';
  end if;
  if p_product_id is null or p_stock < 0 or p_price_cup < 0 then
    raise exception using errcode = '22023', message = 'Revisa el precio y la existencia.';
  end if;

  update public.products
  set stock = p_stock,
      price_cup = p_price_cup,
      active = coalesce(p_active, true),
      updated_at = now()
  where id = p_product_id;

  if not found then
    raise exception using errcode = 'P0002', message = 'Producto no encontrado.';
  end if;
end;
$$;

create or replace function public.admin_update_order(
  p_token text,
  p_order_id uuid,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current_status text;
begin
  if not private.has_admin_session(p_token) then
    raise exception using errcode = '42501', message = 'La sesión administrativa venció.';
  end if;
  if p_status not in ('pendiente', 'confirmado', 'pagado', 'listo', 'completado', 'cancelado') then
    raise exception using errcode = '22023', message = 'Estado de pedido inválido.';
  end if;

  select status into v_current_status
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'Pedido no encontrado.';
  end if;
  if v_current_status = 'cancelado' and p_status <> 'cancelado' then
    raise exception using errcode = 'P0001', message = 'Un pedido cancelado no puede reabrirse automáticamente.';
  end if;

  if p_status = 'cancelado' and v_current_status <> 'cancelado' then
    update public.products p
    set stock = p.stock + i.quantity,
        updated_at = now()
    from public.order_items i
    where i.order_id = p_order_id and i.product_id = p.id;
  end if;

  update public.orders
  set status = p_status, updated_at = now()
  where id = p_order_id;
end;
$$;

create or replace function public.admin_update_settings(
  p_token text,
  p_business_name text,
  p_whatsapp_phone text,
  p_pickup_address text,
  p_payment_copy text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_phone text := regexp_replace(coalesce(p_whatsapp_phone, ''), '\D', '', 'g');
begin
  if not private.has_admin_session(p_token) then
    raise exception using errcode = '42501', message = 'La sesión administrativa venció.';
  end if;
  if btrim(coalesce(p_business_name, '')) = ''
     or btrim(coalesce(p_pickup_address, '')) = ''
     or btrim(coalesce(p_payment_copy, '')) = '' then
    raise exception using errcode = '22023', message = 'Completa los datos del negocio.';
  end if;
  if v_phone <> '' and length(v_phone) < 10 then
    raise exception using errcode = '22023',
      message = 'Escribe el número de WhatsApp con código de país.';
  end if;

  update public.settings
  set business_name = btrim(p_business_name),
      whatsapp_phone = v_phone,
      pickup_address = btrim(p_pickup_address),
      payment_copy = btrim(p_payment_copy),
      updated_at = now()
  where id = 'main';
end;
$$;

create or replace function public.admin_import_legacy_order(p_token text, p_order jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_item jsonb;
  v_inserted integer;
begin
  if not private.has_admin_session(p_token) then
    raise exception using errcode = '42501', message = 'La sesión administrativa venció.';
  end if;

  v_order_id := (p_order ->> 'id')::uuid;
  insert into public.orders
    (id, display_id, customer_name, phone, delivery_method, address,
     payment_method, notes, total_cup, status, created_at, updated_at)
  values
    (v_order_id, p_order ->> 'displayId', p_order ->> 'customerName',
     p_order ->> 'phone', p_order ->> 'deliveryMethod', coalesce(p_order ->> 'address', ''),
     p_order ->> 'paymentMethod', coalesce(p_order ->> 'notes', ''),
     (p_order ->> 'totalCup')::integer, p_order ->> 'status',
     (p_order ->> 'createdAt')::timestamptz, (p_order ->> 'createdAt')::timestamptz)
  on conflict (id) do nothing;
  get diagnostics v_inserted = row_count;

  if v_inserted = 0 then
    return;
  end if;

  for v_item in select value from jsonb_array_elements(coalesce(p_order -> 'items', '[]'::jsonb))
  loop
    insert into public.order_items
      (order_id, product_id, product_name, quantity, unit, price_each_cup, subtotal_cup)
    values
      (v_order_id, v_item ->> 'productId', v_item ->> 'productName',
       (v_item ->> 'quantity')::numeric, v_item ->> 'unit',
       (v_item ->> 'priceEachCup')::integer, (v_item ->> 'subtotalCup')::integer);
  end loop;
end;
$$;

revoke all on function public.get_catalog() from public, anon, authenticated;
revoke all on function public.place_order(jsonb) from public, anon, authenticated;
revoke all on function public.admin_login(text) from public, anon, authenticated;
revoke all on function public.admin_logout(text) from public, anon, authenticated;
revoke all on function public.admin_dashboard(text) from public, anon, authenticated;
revoke all on function public.admin_update_product(text, text, numeric, integer, boolean) from public, anon, authenticated;
revoke all on function public.admin_update_order(text, uuid, text) from public, anon, authenticated;
revoke all on function public.admin_update_settings(text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.admin_import_legacy_order(text, jsonb) from public, anon, authenticated;

grant execute on function public.get_catalog() to anon, authenticated;
grant execute on function public.place_order(jsonb) to anon, authenticated;
grant execute on function public.admin_login(text) to anon, authenticated;
grant execute on function public.admin_logout(text) to anon, authenticated;
grant execute on function public.admin_dashboard(text) to anon, authenticated;
grant execute on function public.admin_update_product(text, text, numeric, integer, boolean) to anon, authenticated;
grant execute on function public.admin_update_order(text, uuid, text) to anon, authenticated;
grant execute on function public.admin_update_settings(text, text, text, text, text) to anon, authenticated;
grant execute on function public.admin_import_legacy_order(text, jsonb) to anon, authenticated;
